"use client";

import React, { useState } from "react";
import { 
  Bot, 
  Sparkles, 
  Code, 
  Server, 
  Database, 
  Cpu, 
  ArrowUpRight, 
  CheckCircle2, 
  DollarSign, 
  Terminal, 
  ChevronRight, 
  Play,
  ArrowRight,
  ExternalLink,
  Laptop,
  Check,
  Zap
} from "lucide-react";

interface Project {
  id: string;
  title: string;
  category: string;
  description: string;
  highlights: string[];
  liveUrl?: string;
  underTheHood: {
    challenge: string;
    solution: string;
    metrics: string[];
  };
}

const PROJECTS: Project[] = [
  {
    id: "healthcare-ai",
    title: "Healthcare AI Assistant",
    category: "AI Integration & Dashboard",
    description: "An intelligent, responsive medical support ecosystem designed to streamline patient intake metrics. The system parses dense diagnostic reports in real time, automates complex medical staff queries securely via isolated backend endpoints, and renders clinical insights on a highly responsive, fluid dashboard.",
    highlights: ["TypeScript base", "Secure data architectures", "Tailwind responsive dashboard"],
    underTheHood: {
      challenge: "Parsing unstructured medical intake notes while strictly adhering to HIPAA privacy standard guidelines, ensuring zero data leakage.",
      solution: "Engineered a local token-stripping pre-processor in TypeScript to sanitize PHI (Protected Health Information) client-side before communicating with LLM API endpoints. Configured automated role-based dashboard encryption and compliant state caching.",
      metrics: ["100% HIPAA pre-processing", "< 1.2s LLM token response time", "Zero server-side data logs"]
    }
  },
  {
    id: "smart-farming",
    title: "Smart Farming Application",
    category: "Full-Stack IoT Platform",
    description: "A sophisticated, data-driven telemetry platform monitoring microclimates, multi-plot soil conditions, and automated irrigation thresholds. Built with responsive frontend interactive charts and optimized MongoDB queries to handle continuous real-time data streaming without performance degradation.",
    highlights: ["Interactive charts", "Optimized MongoDB schema", "Dynamic map queries"],
    liveUrl: "https://smart-farming-lac.vercel.app/",
    underTheHood: {
      challenge: "Handling massive time-series telemetry data from hundreds of simulated soil probes without causing dashboard visual lag or database lockups.",
      solution: "Architected a bucketing schema in MongoDB to aggregate raw readings into 1-hour pre-computed document arrays. Designed real-time sensor sync utilizing canvas-based charting and geo-query indexing to search crop coordinates instantly.",
      metrics: ["94% write-load database reduction", "250ms query response time", "1,500+ updates per second"]
    }
  },
  {
    id: "ai-editor",
    title: "AI-Powered Full-Stack Editor",
    category: "SaaS Dev Tool",
    description: "A next-generation, browser-based integrated development environment featuring lightning-fast hot-reloading and autonomous AI-driven code refactoring. Engineered with secure iframe sandboxing, complex state synchronization, and dynamic API orchestrations to simulate desktop-grade IDE execution inside the browser.",
    highlights: ["API orchestrations", "Iframe sandboxing", "Contextual state sync"],
    liveUrl: "https://google-ai-mocha.vercel.app/",
    underTheHood: {
      challenge: "Safely executing arbitrary JavaScript/React code written by the user or generated by the AI in the browser without threatening main-thread security.",
      solution: "Created a dual-layered isolated iframe sandbox utilizing postMessage communications. Constructed a custom AST (Abstract Syntax Tree) validator to block malicious scripts, paired with a token chunking algorithm for efficient context state sync.",
      metrics: ["100% secure client-side sandbox", "Real-time hot reload in < 15ms", "60% API token usage optimization"]
    }
  }
];

export default function Home() {
  const [activeProject, setActiveProject] = useState<Project | null>(null);
  
  // Contact Form States
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    budget: 5000,
    details: ""
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitStatus, setSubmitStatus] = useState<"idle" | "success" | "error">("idle");
  const [statusMessage, setStatusMessage] = useState("");

  const handleBudgetChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData(prev => ({ ...prev, budget: parseInt(e.target.value) }));
  };

  const getBudgetTierLabel = (budget: number) => {
    if (budget < 3000) return { title: "MVP / Proof of Concept", desc: "Perfect for rapid testing & market validation", color: "text-cyber-green" };
    if (budget < 8000) return { title: "Full Production SaaS", desc: "Polished App Router, database & clean architecture", color: "text-cyber-blue" };
    return { title: "Enterprise High-Performance", desc: "Advanced vector DB search, heavy API scale & high-security", color: "text-cyber-violet" };
  };

  const budgetInfo = getBudgetTierLabel(formData.budget);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setSubmitStatus("idle");

    try {
      const response = await fetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData)
      });
      const data = await response.json();

      if (response.ok) {
        setSubmitStatus("success");
        setStatusMessage(data.message || "Request dispatched!");
        setFormData({ name: "", email: "", budget: 5000, details: "" });
      } else {
        setSubmitStatus("error");
        setStatusMessage(data.error || "Something failed.");
      }
    } catch (err: any) {
      setSubmitStatus("error");
      setStatusMessage("Failed to submit request.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <main className="min-h-screen pb-24 relative">
      
      {/* 1. FLOATING NAVIGATION NAVBAR */}
      <header className="fixed top-4 left-4 right-4 z-40 mx-auto max-w-7xl">
        <div className="glass-panel rounded-full px-6 py-3.5 flex items-center justify-between border-white/5 shadow-lg">
          {/* Logo */}
          <div className="flex items-center gap-2">
            <span className="font-mono text-sm font-black tracking-widest text-slate-200">
              KAIF_DEV_AGENCY <span className="text-cyber-blue">//</span>
            </span>
          </div>

          {/* Navigation Anchors - Desktop */}
          <nav className="hidden md:flex items-center gap-6 font-mono text-xs text-cyber-muted">
            <a href="#capabilities" className="hover:text-cyber-blue transition-colors">// Capabilities</a>
            <a href="#projects" className="hover:text-cyber-blue transition-colors">// Projects</a>
            <a href="#contact" className="hover:text-cyber-blue transition-colors">// Intake Zone</a>
          </nav>

          {/* Live Status Badge */}
          <div className="flex items-center gap-2 bg-black/40 border border-cyber-green/20 px-3 py-1 rounded-full">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-cyber-green opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-cyber-green"></span>
            </span>
            <span className="text-[10px] sm:text-xs font-mono text-slate-300">
              Available — May 2026
            </span>
          </div>
        </div>
      </header>

      {/* Page Container */}
      <div className="max-w-7xl mx-auto px-4 pt-28 space-y-12">
        
        {/* 2. HERO SECTION (The Hook) */}
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
          {/* Left Hero Bento Block */}
          <div className="lg:col-span-7 glass-panel rounded-3xl p-8 sm:p-10 flex flex-col justify-between border-cyber-blue/10 relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-32 h-32 bg-cyber-blue/10 rounded-full filter blur-3xl pointer-events-none group-hover:bg-cyber-blue/20 transition-all duration-500" />
            
            <div className="space-y-6">
              <div className="inline-flex items-center gap-2 bg-cyber-blue/5 border border-cyber-blue/20 px-3.5 py-1.5 rounded-xl">
                <Sparkles className="w-4 h-4 text-cyber-blue animate-pulse" />
                <span className="text-[10px] font-mono tracking-widest text-cyber-blue uppercase">LEAN HIGH-PERFORMANCE SYSTEMS ENGINEER</span>
              </div>
              
              <h1 className="text-4xl sm:text-5xl font-black tracking-tight leading-[1.1] text-slate-100">
                We build <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyber-blue via-cyan-400 to-cyber-violet">high-performance</span> web applications & AI integrations.
              </h1>
              
              <p className="text-gray-400 leading-relaxed text-sm md:text-base max-w-xl">
                Production-grade Next.js and MERN stack architectures engineered solo by Kaif. We eliminate unnecessary framework bloat to deliver blazing-fast, secure, and production-ready digital products tailored to scale seamlessly. From custom LLM integrations to robust full-stack systems, we write the code that powers modern business.
              </p>
            </div>

            <div className="pt-10 flex flex-wrap gap-4">
              <a 
                href="#contact" 
                className="px-6 py-3.5 rounded-2xl bg-cyber-blue text-black font-semibold text-sm hover:shadow-[0_0_20px_rgba(0,240,255,0.4)] transition-all duration-300 flex items-center gap-2 group-hover:scale-105 transform"
              >
                Let's Build <ArrowRight className="w-4 h-4" />
              </a>
              <a 
                href="#projects" 
                className="px-6 py-3.5 rounded-2xl bg-white/2 border border-white/5 hover:border-white/15 text-slate-300 hover:text-slate-100 text-sm font-semibold transition-all duration-300"
              >
                Explore Case Studies
              </a>
            </div>
          </div>

          {/* Right Hero Code Terminal Block */}
          <div className="lg:col-span-5 glass-panel rounded-3xl p-6 border-white/5 flex flex-col justify-between font-mono text-xs relative overflow-hidden bg-black/50">
            <div className="flex items-center justify-between border-b border-white/5 pb-4 mb-4">
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-rose-500/80"></span>
                <span className="w-3 h-3 rounded-full bg-amber-500/80"></span>
                <span className="w-3 h-3 rounded-full bg-emerald-500/80"></span>
              </div>
              <span className="text-[10px] text-cyber-muted">bash // core-compiler</span>
            </div>

            <div className="flex-1 space-y-3.5 text-slate-400">
              <p className="text-cyber-muted"># Building production application...</p>
              <p className="text-slate-300 flex items-center gap-2">
                <span className="text-cyber-violet">&gt;</span> npm run build
              </p>
              <div className="p-3 rounded-xl bg-white/2 border border-white/5 space-y-1.5 text-[11px]">
                <p className="text-slate-300">▲ Next.js 15.2 - Creating an optimized production build...</p>
                <p className="text-cyber-green">✓ Compiled successfully</p>
                <p className="text-cyber-blue">✓ Collecting page data</p>
                <p className="text-cyber-blue">✓ Automatically optimizing pages</p>
              </div>
              <p className="text-slate-300 flex items-center gap-2">
                <span className="text-cyber-violet">&gt;</span> npm start
              </p>
              <div className="pt-2 text-cyber-muted flex items-center gap-2">
                <span className="w-1.5 h-3 bg-cyber-blue animate-pulse"></span>
                <span>Ready on http://localhost:3000</span>
              </div>
            </div>

            <div className="mt-8 border-t border-white/5 pt-4 flex items-center justify-between text-[10px] text-cyber-muted">
              <span>LATENCY: 14ms</span>
              <span className="text-cyber-green">STABLE BUILD</span>
            </div>
          </div>
        </section>

        {/* 3. TECH STACK & CAPABILITIES BENTO GRID */}
        <section id="capabilities" className="space-y-6">
          <div className="space-y-2">
            <h2 className="text-xs font-mono tracking-widest text-cyber-violet uppercase">// TECHNICAL CORE</h2>
            <p className="text-2xl font-bold tracking-tight text-slate-100">Bento capabilities grid</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
            {/* Card A: MERN & Next.js */}
            <div className="md:col-span-8 glass-panel rounded-3xl p-8 border-cyber-blue/10 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4">
                <Laptop className="w-5 h-5 text-cyber-blue/40 group-hover:text-cyber-blue transition-colors" />
              </div>
              
              <div className="space-y-4 max-w-xl">
                <span className="text-[10px] font-mono tracking-widest text-cyber-blue">01 // FULL-STACK CORE</span>
                <h3 className="text-xl font-bold text-slate-200">The MERN & Next.js Ecosystem</h3>
                <p className="text-gray-400 leading-relaxed text-sm md:text-base">
                  We specialize in crafting rock-solid backend architectures combined with lightning-fast reactive interfaces. By leveraging Next.js App Router server-side capabilities, structured TypeScript data models, and highly optimized MongoDB schemas, we ensure your application remains blazing fast under heavy production traffic.
                </p>

                {/* Tech Badges */}
                <div className="pt-4 flex flex-wrap gap-2">
                  {["Next.js 15 (App Router)", "React 19", "TypeScript", "NodeJS", "Express", "MongoDB", "Tailwind CSS v4"].map((tech) => (
                    <span 
                      key={tech} 
                      className="cyber-badge px-3 py-1.5 rounded-lg text-xs hover:border-cyber-blue/40 hover:text-slate-100 transition-all duration-300"
                    >
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Card B: AI Integrations */}
            <div className="md:col-span-4 glass-panel rounded-3xl p-8 border-cyber-violet/10 relative overflow-hidden group flex flex-col justify-between">
              <div className="absolute top-0 right-0 p-4">
                <Bot className="w-5 h-5 text-cyber-violet/40 group-hover:text-cyber-violet transition-colors" />
              </div>
              
              <div className="space-y-4">
                <span className="text-[10px] font-mono tracking-widest text-cyber-violet">02 // COGNITIVE INTEGRATIONS</span>
                <h3 className="text-xl font-bold text-slate-200">AI Capabilities</h3>
                <p className="text-gray-400 leading-relaxed text-sm md:text-base">
                  Supercharge your application workflows with intelligent automation. We build custom serverless vector pipelines, low-latency streaming LLM chat structures, and highly specialized RAG (Retrieval-Augmented Generation) database systems using Google AI Studio. Turn unstructured business data into autonomous agents that act instantly.
                </p>
              </div>

              <div className="pt-6">
                <div className="p-3 bg-black/40 border border-cyber-violet/20 rounded-2xl flex items-center justify-between text-[11px] font-mono">
                  <span className="text-cyber-muted">RAG Vector Sync:</span>
                  <span className="text-cyber-violet animate-pulse flex items-center gap-1.5">
                    <Zap className="w-3.5 h-3.5" /> ACTIVE
                  </span>
                </div>
              </div>
            </div>

            {/* Card C: Repository Architecture */}
            <div className="md:col-span-5 glass-panel rounded-3xl p-8 border-white/5 relative overflow-hidden group flex flex-col justify-between">
              <div className="space-y-4">
                <span className="text-[10px] font-mono tracking-widest text-slate-500">03 // STABLE PIPELINES</span>
                <h3 className="text-xl font-bold text-slate-200">Clean Repository Practices</h3>
                <p className="text-gray-400 leading-relaxed text-sm md:text-base">
                  Maintainable codebases are non-negotiable. Every repository we deliver conforms to rigid ESLint parameters, clean module segregation, and strict separation of API routes from presentation logic. This flawless structure guarantees that any future developer can jump into the codebase and scale it instantly without breaking production.
                </p>
              </div>

              <div className="pt-6 space-y-2 font-mono text-[11px] text-cyber-muted">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-cyber-green" /> Strict ESLint & TypeScript Compilation
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-cyber-green" /> Separation of Routes & Core Queries
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-cyber-green" /> 100% Client-Side Payload Sanitization
                </div>
              </div>
            </div>

            {/* Card D: Performance Stats */}
            <div className="md:col-span-7 glass-panel rounded-3xl p-8 border-cyber-green/10 relative overflow-hidden group flex flex-col justify-between">
              <div className="absolute top-0 right-0 p-4">
                <Zap className="w-5 h-5 text-cyber-green/40 group-hover:text-cyber-green transition-colors" />
              </div>

              <div className="space-y-4">
                <span className="text-[10px] font-mono tracking-widest text-cyber-green">04 // USER PERFORMANCE</span>
                <h3 className="text-xl font-bold text-slate-200">Guaranteed Production Metrics</h3>
                <p className="text-gray-400 leading-relaxed text-sm md:text-base">
                  Performance directly dictates conversion rates, user retention, and organic SEO ranking. We deploy highly optimized, server-rendered production bundles designed to maintain flawless core web vitals and instantaneous client-side navigation.
                </p>
              </div>

              <div className="pt-8 grid grid-cols-3 gap-4 text-center font-mono">
                <div className="p-3.5 bg-white/2 border border-white/5 rounded-2xl">
                  <div className="text-2xl font-black text-cyber-green">99+</div>
                  <div className="text-[10px] text-cyber-muted mt-1">LIGHTHOUSE</div>
                </div>
                <div className="p-3.5 bg-white/2 border border-white/5 rounded-2xl">
                  <div className="text-2xl font-black text-cyber-blue">&lt;15ms</div>
                  <div className="text-[10px] text-cyber-muted mt-1">HOT RELOAD</div>
                </div>
                <div className="p-3.5 bg-white/2 border border-white/5 rounded-2xl">
                  <div className="text-2xl font-black text-cyber-violet">0.0</div>
                  <div className="text-[10px] text-cyber-muted mt-1">CRASH RATE</div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* 4. FLAGSHIP PROJECTS (Show, Don't Tell) */}
        <section id="projects" className="space-y-6">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
            <div className="space-y-2">
              <h2 className="text-xs font-mono tracking-widest text-cyber-blue uppercase">// VERIFIED WORK</h2>
              <p className="text-2xl font-bold tracking-tight text-slate-100">Flagship Projects Showcase</p>
            </div>
            <p className="text-xs font-mono text-cyber-muted">
              *CLICK &apos;UNDER THE HOOD&apos; TO DISCOVER REPO STRATEGIES
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {PROJECTS.map((proj, idx) => (
              <div 
                key={proj.id} 
                className="glass-panel rounded-3xl p-6 border-white/5 flex flex-col justify-between relative overflow-hidden group hover:bg-[#0d0d24]/45 transition-all duration-500"
              >
                {/* Background index label */}
                <div className="absolute -bottom-8 -right-4 font-mono text-[90px] font-black text-white/[0.01] group-hover:text-white/[0.03] transition-colors pointer-events-none select-none">
                  0{idx + 1}
                </div>

                <div className="space-y-5">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-mono tracking-wider text-cyber-muted bg-white/2 px-2.5 py-1 rounded-md border border-white/5">
                      {proj.category}
                    </span>
                    {proj.liveUrl && (
                      <a 
                        href={proj.liveUrl} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="p-1.5 rounded-lg bg-cyber-blue/10 border border-cyber-blue/30 text-cyber-blue hover:bg-cyber-blue hover:text-black transition-all duration-300"
                        title="Live Demo Preview"
                      >
                        <ExternalLink className="w-4 h-4" />
                      </a>
                    )}
                  </div>

                  <div>
                    <h3 className="text-lg font-bold text-slate-200 group-hover:text-cyber-blue transition-colors">
                      {proj.title}
                    </h3>
                    <p className="text-gray-400 leading-relaxed text-xs md:text-sm mt-2">
                      {proj.description}
                    </p>
                  </div>

                  {/* Highlights Bulletpoints */}
                  <ul className="space-y-1.5 pt-1">
                    {proj.highlights.map((hl) => (
                      <li key={hl} className="text-[11px] font-mono text-slate-400 flex items-center gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-cyber-blue"></span>
                        {hl}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="pt-8">
                  <button 
                    onClick={() => setActiveProject(proj)}
                    className="w-full py-2.5 font-mono text-xs font-semibold rounded-xl bg-white/2 hover:bg-white/5 border border-white/5 hover:border-white/15 text-slate-300 hover:text-white transition-all duration-300 flex items-center justify-center gap-1.5"
                  >
                    <Terminal className="w-3.5 h-3.5" />
                    <span>Under the Hood</span>
                    <ArrowRight className="w-3.5 h-3.5 text-cyber-blue group-hover:translate-x-1 transition-transform duration-300" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* 5. ACTION ZONE (Contact & Intake) */}
        <section id="contact" className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
          
          {/* Left Details Info */}
          <div className="lg:col-span-5 glass-panel rounded-3xl p-8 border-cyber-blue/10 flex flex-col justify-between relative overflow-hidden">
            <div className="space-y-6">
              <span className="text-[10px] font-mono tracking-widest text-cyber-blue uppercase">// INTAKE DEPLOYMENT</span>
              <h2 className="text-3xl font-black text-slate-100">Let&apos;s engineer your next digital asset.</h2>
              <p className="text-gray-400 leading-relaxed text-sm md:text-base">
                Submit your project specifications, required features, and timeline expectations below. Our engineering desk will thoroughly analyze your technical architecture requirements and schedule a comprehensive, deep-dive Technical Strategy consultation within 12 hours. Let&apos;s build a system that works for you.
              </p>
            </div>

            <div className="pt-10 space-y-4 text-xs font-mono text-slate-400">
              <div className="flex items-center gap-3">
                <span className="w-2.5 h-2.5 rounded-full bg-cyber-green animate-pulse"></span>
                <span>Response SLA: <strong>&lt; 12 Hours</strong></span>
              </div>
              <div className="flex items-center gap-3">
                <span className="w-2.5 h-2.5 rounded-full bg-cyber-blue"></span>
                <span>Project Slots Left: <strong>2/3 for Q2</strong></span>
              </div>
              <div className="flex items-center gap-3">
                <span className="w-2.5 h-2.5 rounded-full bg-cyber-violet"></span>
                <span>Pricing Model: <strong>Milestone / Fixed Cap</strong></span>
              </div>
            </div>

            <div className="pt-12 border-t border-white/5 text-[10px] font-mono text-cyber-muted">
              SECURE DEPLOYMENT ENDPOINT ENCRYPTED
            </div>
          </div>

          {/* Right Intake Contact Form */}
          <div className="lg:col-span-7 glass-panel rounded-3xl p-8 border-white/5 relative bg-[#070712]/50 flex flex-col justify-center min-h-[400px]">
            {submitStatus === "success" ? (
              <div className="space-y-6 font-mono text-xs text-left animate-in fade-in zoom-in-95 duration-500">
                <div className="flex items-center gap-2 border-b border-cyber-green/20 pb-4">
                  <div className="w-2.5 h-2.5 rounded-full bg-cyber-green animate-pulse"></div>
                  <span className="text-cyber-green font-bold uppercase tracking-wider">INTAKE TRANSMISSION SECURED</span>
                </div>
                
                <div className="space-y-4 bg-black/40 border border-cyber-green/10 rounded-2xl p-6">
                  <div className="flex items-start gap-2">
                    <span className="text-cyber-green font-bold shrink-0">[SYSTEM]:</span>
                    <span className="text-slate-300 leading-relaxed">Intake payload compiled successfully.</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <span className="text-cyber-blue font-bold shrink-0">[STATUS]:</span>
                    <span className="text-slate-300 leading-relaxed">Transmitted securely to Kaif&apos;s desk via Resend Routing.</span>
                  </div>
                  <div className="flex items-start gap-2">
                    <span className="text-cyber-violet font-bold shrink-0">[TIMER]:</span>
                    <span className="text-slate-300 leading-relaxed">Engineering review initiated. Expect a response within 12 hours.</span>
                  </div>
                </div>

                <button 
                  onClick={() => setSubmitStatus("idle")}
                  className="px-5 py-3 rounded-xl border border-white/5 hover:border-cyber-blue/30 text-cyber-blue hover:bg-cyber-blue/5 text-[10px] sm:text-xs font-bold transition-all duration-300"
                >
                  &gt; Send Another Transmission
                </button>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-6 animate-in fade-in duration-300">
                
                {/* Row 1: Name and Email */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label htmlFor="name" className="block text-[11px] font-mono text-cyber-muted">NAME / ENTITY *</label>
                    <input 
                      type="text" 
                      id="name"
                      required
                      value={formData.name}
                      onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                      placeholder="John Doe / Tech Director" 
                      className="w-full px-4 py-3 text-xs bg-white/2 focus:bg-white/4 border border-white/5 focus:border-cyber-blue/40 rounded-xl text-slate-100 placeholder-slate-600 focus:outline-none transition-all duration-300 font-mono"
                    />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="email" className="block text-[11px] font-mono text-cyber-muted">EMAIL COORDINATES *</label>
                    <input 
                      type="email" 
                      id="email"
                      required
                      value={formData.email}
                      onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                      placeholder="john@company.com" 
                      className="w-full px-4 py-3 text-xs bg-white/2 focus:bg-white/4 border border-white/5 focus:border-cyber-blue/40 rounded-xl text-slate-100 placeholder-slate-600 focus:outline-none transition-all duration-300 font-mono"
                    />
                  </div>
                </div>

                {/* Row 2: Cyber Budget Slider */}
                <div className="space-y-3 p-4 bg-black/30 border border-white/5 rounded-2xl">
                  <div className="flex justify-between items-center">
                    <label htmlFor="budget" className="text-[11px] font-mono text-cyber-muted">ESTIMATED BUDGET</label>
                    <span className="text-xs font-mono font-bold text-cyber-blue bg-cyber-blue/5 border border-cyber-blue/20 px-2 py-0.5 rounded-md">
                      ${formData.budget.toLocaleString()} USD
                    </span>
                  </div>

                  <input 
                    type="range" 
                    id="budget"
                    min="1000" 
                    max="15000" 
                    step="500"
                    value={formData.budget}
                    onChange={handleBudgetChange}
                    className="w-full h-1.5 bg-white/10 rounded-lg appearance-none cursor-pointer accent-cyber-blue focus:outline-none"
                  />

                  <div className="pt-2">
                    <div className={`text-xs font-bold font-mono transition-colors duration-300 ${budgetInfo.color}`}>
                      {budgetInfo.title}
                    </div>
                    <div className="text-[10px] text-cyber-muted leading-relaxed mt-0.5">
                      {budgetInfo.desc}
                    </div>
                  </div>
                </div>

                {/* Row 3: Project Specifications */}
                <div className="space-y-2">
                  <label htmlFor="details" className="block text-[11px] font-mono text-cyber-muted">PROJECT SPECIFICATIONS / SCOPE *</label>
                  <textarea 
                    id="details"
                    required
                    rows={4}
                    value={formData.details}
                    onChange={(e) => setFormData(prev => ({ ...prev, details: e.target.value }))}
                    placeholder="Describe your system architecture, required features, integration scope, or timeline constraints..."
                    className="w-full px-4 py-3 text-xs bg-white/2 focus:bg-white/4 border border-white/5 focus:border-cyber-blue/40 rounded-xl text-slate-100 placeholder-slate-600 focus:outline-none transition-all duration-300 font-mono resize-none"
                  />
                </div>

                {/* Submit States Notification */}
                {submitStatus === "error" && (
                  <div className="p-4 rounded-xl border text-xs font-mono bg-rose-500/5 border-rose-500/30 text-rose-400">
                    ✗ {statusMessage}
                  </div>
                )}

                {/* Submit Button */}
                <button 
                  type="submit"
                  disabled={isSubmitting}
                  className="w-full py-4 text-xs font-bold font-mono rounded-xl bg-cyber-blue text-black hover:shadow-[0_0_25px_rgba(0,240,255,0.45)] disabled:opacity-50 transition-all duration-300 flex items-center justify-center gap-2"
                >
                  {isSubmitting ? (
                    <>DISPATCHING SECURE REQUEST...</>
                  ) : (
                    <>DISPATCH SYSTEM INTAKE <ChevronRight className="w-4 h-4" /></>
                  )}
                </button>
              </form>
            )}
          </div>

        </section>

      </div>

      {/* 6. MODAL OVERLAY: CASE STUDIES / UNDER THE HOOD */}
      {activeProject && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-300">
          <div className="w-full max-w-2xl glass-panel rounded-3xl border border-cyber-blue/30 shadow-[0_0_50px_rgba(0,240,255,0.2)] overflow-hidden flex flex-col max-h-[90vh]">
            
            {/* Header */}
            <div className="p-6 bg-cyber-card border-b border-white/5 flex justify-between items-center">
              <div>
                <span className="text-[10px] font-mono text-cyber-blue tracking-wider font-bold">CASE STUDY // DEEP DIVE</span>
                <h3 className="text-xl font-black text-slate-100">{activeProject.title}</h3>
              </div>
              <button 
                onClick={() => setActiveProject(null)}
                className="p-1.5 rounded-lg bg-white/2 hover:bg-white/10 text-cyber-muted hover:text-slate-100 border border-white/5 transition-colors font-mono text-xs"
              >
                CLOSE [X]
              </button>
            </div>

            {/* Body Contents */}
            <div className="p-6 overflow-y-auto space-y-6 text-sm leading-relaxed">
              
              {/* Challenge */}
              <div className="space-y-2">
                <div className="text-xs font-mono text-cyber-violet flex items-center gap-1.5">
                  <Terminal className="w-3.5 h-3.5" /> THE ENGINEERING CHALLENGE
                </div>
                <p className="text-slate-300 bg-white/[0.01] border border-white/5 p-4 rounded-2xl">
                  {activeProject.underTheHood.challenge}
                </p>
              </div>

              {/* Solution */}
              <div className="space-y-2">
                <div className="text-xs font-mono text-cyber-blue flex items-center gap-1.5">
                  <Code className="w-3.5 h-3.5" /> HOW WE SOLVED IT UNDER THE HOOD
                </div>
                <p className="text-slate-300 bg-white/[0.01] border border-white/5 p-4 rounded-2xl">
                  {activeProject.underTheHood.solution}
                </p>
              </div>

              {/* Metrics / Achievements */}
              <div className="space-y-3">
                <div className="text-xs font-mono text-cyber-green flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5" /> ENGINEERING METRICS SECURED
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  {activeProject.underTheHood.metrics.map((metric, index) => (
                    <div 
                      key={index} 
                      className="p-3 bg-cyber-green/5 border border-cyber-green/20 rounded-xl text-center text-xs font-mono text-slate-200"
                    >
                      {metric}
                    </div>
                  ))}
                </div>
              </div>

            </div>

            {/* Footer */}
            <div className="p-4 bg-cyber-card border-t border-white/5 flex gap-3">
              {activeProject.liveUrl ? (
                <a 
                  href={activeProject.liveUrl} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex-1 py-3 text-center text-xs font-mono font-bold rounded-xl bg-cyber-blue text-black hover:shadow-[0_0_15px_rgba(0,240,255,0.4)] transition-all duration-300 flex items-center justify-center gap-1.5"
                >
                  Live Preview <ExternalLink className="w-4 h-4" />
                </a>
              ) : (
                <div className="flex-1 py-3 text-center text-xs font-mono font-semibold rounded-xl bg-white/5 border border-white/10 text-slate-400">
                  Secure Enterprise Environment (HIPAA Private)
                </div>
              )}
              <button 
                onClick={() => setActiveProject(null)}
                className="px-6 py-3 text-xs font-mono rounded-xl bg-white/2 hover:bg-white/5 border border-white/5 text-slate-300 hover:text-white transition-colors"
              >
                Close Spec
              </button>
            </div>

          </div>
        </div>
      )}

    </main>
  );
}
